"use client";

import { useState } from "react";
import { Search as SearchIcon, Filter, Camera } from "lucide-react";
import styles from "./page.module.css";

export default function SearchPage() {
  const [query, setQuery] = useState("");
  const [isSearching, setIsSearching] = useState(false);

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>AI Discovery</h1>
        <p className={styles.subtitle}>Search through your media library using semantic AI tags generated by Cloudinary.</p>
      </header>

      <div className={styles.searchSection}>
        <div className={styles.searchBar}>
          <SearchIcon size={24} className={styles.searchIcon} />
          <input 
            type="text" 
            placeholder="Search for 'solar panels', 'mangroves', or 'community meeting'..." 
            className={styles.searchInput}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          <button className={styles.filterButton}>
            <Filter size={20} />
          </button>
        </div>
        
        <div className={styles.popularTags}>
          <span className={styles.tagsLabel}>Suggested:</span>
          {["Reforestation", "Solar Energy", "Water Cleanup", "Before & After", "Field Operations"].map((tag) => (
            <button key={tag} className={styles.tagBadge} onClick={() => setQuery(tag)}>
              {tag}
            </button>
          ))}
        </div>
      </div>

      <div className={styles.resultsArea}>
        {query ? (
          <div className={styles.resultsGrid}>
             {/* Mock search result */}
             <div className={`glass-panel ${styles.resultCard}`}>
                <div className={styles.resultImagePlaceholder}>
                  <Camera size={32} opacity={0.3} />
                </div>
                <div className={styles.resultInfo}>
                  <p className={styles.resultProject}>Coastal Reforestation Initiative</p>
                  <div className={styles.resultTags}>
                    <span className={styles.resultTag}>mangroves</span>
                    <span className={styles.resultTag}>coastline</span>
                    <span className={styles.resultTag}>planting</span>
                  </div>
                </div>
             </div>
          </div>
        ) : (
          <div className={styles.emptyState}>
            <SearchIcon size={48} className={styles.emptyIcon} />
            <h3>Start typing to discover media</h3>
            <p>Our AI has analyzed and tagged all your field evidence automatically.</p>
          </div>
        )}
      </div>
    </div>
  );
}
